In [1]:
 # Iterating Over Arrays
import numpy as np
fruits = np.array(['apple', 'banana', 'cherry'])
for fruit in fruits:
    print("fruits=",fruit)

fruits= apple
fruits= banana
fruits= cherry


In [2]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr:
    print("rows =",row)

rows = [1 2]
rows = [3 4]
rows = [5 6]


In [4]:
arr = np.array([[1, 2], [3, 4]])
for val in arr.flat:
    print(val, end=" ")

1 2 3 4 

In [6]:
arr = np.array([1, 2, 3,4])
#p.nditer is used to loop through each element of the array one by one.
#op_flags=['readwrite'] allows modifying the array values while iterating.
for x in np.nditer(arr, op_flags=['readwrite']):
    x[...]=x**3  
print("new =",arr)    

new = [ 1  8 27 64]


In [7]:
# np.ndenumerate() gives both index and value, which is helpful in debugging
arr = np.array([[100, 200], [300, 400]])
for index,value in np.ndenumerate(arr):
    print(f"index is {index}",f" value is {value}")

index is (0, 0)  value is 100
index is (0, 1)  value is 200
index is (1, 0)  value is 300
index is (1, 1)  value is 400


In [11]:
#  numpy.random
a=np.random.rand(5)
bm=np.random.rand(2,3)
print(a)
print(bm)

[0.05054775 0.72697653 0.46876521 0.53554067 0.78645057]
[[0.39343825 0.57184153 0.0344996 ]
 [0.73774486 0.81446954 0.31833615]]


In [12]:
b=np.random.randint(10,50, size=7)
print(b)

[38 39 42 40 32 41 24]


In [13]:
c=np.random.randn(2,2,2)
print(c)

[[[-0.38772665  1.18258073]
  [-0.89790138 -0.20901758]]

 [[-0.01938514  0.45250335]
  [ 1.35241171 -0.00435527]]]


In [17]:
items = ['apple', 'banana', 'cherry']
arr=np.random.choice(items, size= 2)
print(arr)

['apple' 'apple']


In [18]:
arr = np.array([1, 2, 3, 4, 5]) # shuffle changes original array
np.random.shuffle(arr) # permutation also do shuffling  but creates new array
print( arr)

[5 2 4 1 3]
