In [28]:
# NumPy String Functions
import numpy as np
names = np.array(['Alice', 'BOB', 'CChArLiE'])
print(np.char.lower(names))
print(np.char.upper(names))

['alice' 'bob' 'ccharlie']
['ALICE' 'BOB' 'CCHARLIE']


In [29]:
arr = np.array(['hello', 'world'])
print(np.char.capitalize(arr))

['Hello' 'World']


In [30]:
first = np.array(['John', 'Jane'])
last = np.array(['Doe', 'Smith'])
print(np.char.add(first,last))

['JohnDoe' 'JaneSmith']


In [31]:
words = np.array(['Hi', 'Bye'])
print(np.char.multiply(words,2))

['HiHi' 'ByeBye']


In [32]:
arr = np.array(['Hi', 'Hello'])
print(np.char.center(arr, 10, fillchar='*'))

['****Hi****' '**Hello***']


In [33]:
arr = np.array(['  apple  ', '  banana'])
print(np.char.strip(arr))

['apple' 'banana']


In [34]:
import numpy as np
arr = np.array(['I hate bugs', 'Bugs are bad'])
print(np.char.replace(arr,'bugs','feature'))

['I hate feature' 'Bugs are bad']


In [35]:
emails = np.array(['user@example.com', 'ad@'])
print(np.char.find(emails,'@'))

[4 2]


# NumPy DateTime Functions

In [36]:
date1=np.datetime64('2025-05-08')
print(date1)

2025-05-08


In [37]:
datetime1 = np.datetime64('2025-05-08T10:30')
print(datetime1)

2025-05-08T10:30


In [38]:
# np.datetime64().astype(str) – Convert to String
date1=np.datetime64('2025-05-08')
print(date1.astype(str))

2025-05-08


In [39]:
date1=np.datetime64('2025-05-08','M') # sertting up precision using(D,M,Y,h,m,s)
print(date1)
date2=np.datetime64('2025-05-08T12','Y')
print(date2)
dates=np.arange('2006-08-30','2006-09-07',dtype='datetime64')
print(dates)
d1 = np.datetime64('2026-01-10')
d2 = np.datetime64('2006-08-30')
print(d1-d2)
print("Today:", np.datetime64('today'))

2025-05
2025
['2006-08-30' '2006-08-31' '2006-09-01' '2006-09-02' '2006-09-03'
 '2006-09-04' '2006-09-05' '2006-09-06']
7073 days
Today: 2026-01-09


In [44]:
#fmt='%d' means the numbers are saved as integers.
#delimiter="" means values are written without any separator (usually a comma or space is used).
data = np.array([[85, 90], [75, 80], [95, 92]])
np.savetxt('scores1.csv',data,delimiter=",",fmt='%d')
loaded_scores = np.loadtxt('scores1.csv',delimiter=",")
print(loaded_scores)

[[85. 90.]
 [75. 80.]
 [95. 92.]]


In [46]:
arr = np.array([1, 2, 3, 4])
np.save("my_array.npy", arr)
print(np.load("my_array.npy"))

[1 2 3 4]


In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.savez("multiple_arrays.npz", array1=a, array2=b)
data = np.load("multiple_arrays.npz")
print(data['array1'])

[1 2 3]
