In [31]:
 # indexing and slicing
import numpy as np
arr=np.arange(9)
print(arr)
print(arr[:8])
print(arr[3:6])
print(arr[8])
print(arr[1:8:2])
print(arr[1:8:3])
print(arr[1::3])
print(arr[8:0:-1])

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]
[3 4 5]
8
[1 3 5 7]
[1 4 7]
[1 4 7]
[8 7 6 5 4 3 2 1]


In [11]:
import numpy as np
a=np.array([1,2,3,4])
b=np.zeros((3,5))
c=np.ones((4,4))
d=np.arange(9)
print("Array a:", a)
print("Array b:", b)
print("Array c:", c)
print("Array d:", d)


Array a: [1 2 3 4]
Array b: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array c: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array d: [0 1 2 3 4 5 6 7 8]


In [ ]:
# Numpy Fundamentals Practice 
# This notebook covers numpy from basic to advanced