In [ ]:
# broadcasting in numpy
import numpy as np
c=np.array([[50, 60, 70],[80, 90, 100]])
b=12
curve = np.array([1, 2, 3])
print("sum =",c+b)
print("power =",c**b)
print("product =",c*curve)
print("subtraction =",c-curve)

sum = [[ 62  72  82]
 [ 92 102 112]]
power = [[ 4332952041775828992    66535302272909312  6229145717836288000]
 [ 5355061431920230400 -8562031566944792576  2003764205206896640]]
product = [[ 50 120 210]
 [ 80 180 300]]
subtraction = [[49 58 67]
 [79 88 97]]


In [10]:
# reshaping and resizing arrays
curve = np.array([1, 2, 3,4,5,6,7,8])
b=curve.reshape(4,2)
print("b =",b)
c=b.flatten()
print("c =", c)
b=np.resize(b,(5,5))
print("b =",b)
b=b.reshape(5,5)
print("b =",b)


b = [[1 2]
 [3 4]
 [5 6]
 [7 8]]
c = [1 2 3 4 5 6 7 8]
b = [[1 2 3 4 5]
 [6 7 8 1 2]
 [3 4 5 6 7]
 [8 1 2 3 4]
 [5 6 7 8 1]]
b = [[1 2 3 4 5]
 [6 7 8 1 2]
 [3 4 5 6 7]
 [8 1 2 3 4]
 [5 6 7 8 1]]
