In [2]:
# elementwise arithmetic operations
import  numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,5,89,4,7])
print("sum =",a+b)
print("product =",a*b)
print("division =",a/b)
print("exponent =",a**b)
print("modulo =",a%b)
# scalar operations
print(a+3)
print(a**3)
print(a/3)


sum = [ 2  7 92  8 12]
product = [  1  10 267  16  35]
division = [1.         0.4        0.03370787 1.         0.71428571]
exponent = [                   1                   32 -7611887770737671773
                  256                78125]
modulo = [0 2 3 0 5]
[4 5 6 7 8]
[  1   8  27  64 125]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [11]:
# comparison operations
a = np.array([1,2,3,4,5])
print(a>=3)
print(a<3)
print(a==3)
# logical operations
arr = np.array([33,44,55,67,78])
print((arr>70)| (arr<60))
print((arr>70) & (arr<767))
print((arr==70) | (arr<767))
print((arr==70) | (arr>767))

[False False  True  True  True]
[ True  True False False False]
[False False  True False False]
[ True  True  True False  True]
[False False False False  True]
[ True  True  True  True  True]
[False False False False False]


In [12]:
# aggregate functions
arr = np.array([33,44,55,67,78])
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.var())
print(arr.sum())
print(arr.std())

33
78
55.4
255.44
277
15.982490419205638


In [16]:
# axis based aggregations
arr = np.array([[80, 90, 70],[60, 85, 75]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.min(axis=1))
print(arr.mean(axis=1))


[140 175 145]
[240 220]
[70 60]
[80.         73.33333333]
