In [4]:
# NUMPY AND LINEAR ALGEBRA
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A,B))
print(A*B)
print(np.transpose(A))
c= np.array([[1, 2], [3, 4]])

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]


In [ ]:
import numpy as np
c= np.array([[1, 2], [3, 4]])
det=np.linalg.det(c)
inver=np.linalg.inv(c)
print(det)
print(inver)
A = np.array([[4, -2], [1, 1]])
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues =", eigvals)
print("Eigenvectors =", eigvecs)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues = [3. 2.]
Eigenvectors = [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
# for solving equation AX=b
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 18])
X=np.linalg.solve(A,b)
print("value of x =", X)

value of x = [1.2 5.6]


In [8]:
#  Numpy Handling Missing Data
data = np.array([1, 2, np.nan, 4, 5, np.nan]) # basically np.nan is written for handling of missing values
print("data =",data)

data = [ 1.  2. nan  4.  5. nan]


In [ ]:
#checking for Missing Data (np.isnan())
data = np.array([1, 2, np.nan, 4, 5, np.nan])
is_nan=np.isnan(data)
print("is_nan =",is_nan)

is_nan = [False False  True False False  True]


In [ ]:
#Replacing Missing Values (np.nan_to_num())
data = np.array([1, 2, np.nan, 4, 5, np.nan])
is_data=np.nan_to_num(data)
print("is_data =",is_data)

is_data = [1. 2. 0. 4. 5. 0.]


In [ ]:
#Filling Missing Values with a Specific Value (np.where())
data = np.array([1, 2, np.nan, 4, 5, np.nan])
where_data=np.where(data)
print("where_data =",where_data)

where_data = (array([0, 1, 2, 3, 4, 5]),)


In [14]:
#Removing Missing Data (np.isnan())
data = np.array([1, 2, np.nan, 4, 5, np.nan])
cleaneddata=data[~np.isnan(data)]
print("cleaneddata =",cleaneddata)

cleaneddata = [1. 2. 4. 5.]


In [16]:
#Using np.nanmean(), np.nanstd(), etc.
# Using np.nanmean() to compute the mean while ignoring NaN
data = np.array([1, 2, np.nan, 4, 5, np.nan])
mean=np.nanmean(data)
std=np.nanstd(data)
print("mean =",mean)
print("std =",std)

mean = 3.0
std = 1.5811388300841898
